# Tikz figures are externalised (\tikzexternalize in main.tex): the first
# compile writes figures_pdf/<name>.pdf, later ones just include it. That needs
# -shell-escape so pdflatex can invoke itself once per figure. latexmk reads
# this file automatically, so ctrl+alt+B picks it up with no editor config.
$pdflatex = 'pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error %O %S';

# Externalisation decides freshness from an md5 of the picture body, which
# covers figures/<name>.tex but not the PNGs that body references. So a
# figure regenerated by MATLAB can leave a stale cached PDF behind. Drop any
# cached PDF older than its source or its PNGs, and the compile rebuilds it.
# Only files with a matching figures/<name>.tex are considered, so the
# auto-named legend snippets are left alone.
{
    my $figdir = 'figures';

    # every figure the document draws, from the \tikzfig{...} calls themselves,
    # plus the appendix figures pulled in with a plain \input{figures/...}
    my %want;
    my @plain;
    for my $tex ('main.tex', grep { $_ !~ /\.OLD\.tex\z/ } glob('sections/*.tex')) {
        open my $fh, '<', $tex or next;
        while (<$fh>) {
            next if /^\s*%/;
            $want{$1} = 1 while /\\tikzfig\{([^}]+)\}/g;
            push @plain, "$figdir/$1.tex"
                while /\\input\{(?:\.\.?\/)*figures\/([^}]+?)(?:\.tex)?\}/g;
        }
        close $fh;
    }

    my $stale = 0;
    for my $name (sort keys %want) {
        my $src = "$figdir/$name.tex";
        next unless -e $src;
        my $pdf = "figures_pdf/$name.pdf";

        my $why = '';
        if (!-e $pdf) {
            $why = 'no cached PDF';
        } else {
            my $tpdf = (stat $pdf)[9];
            if ((stat $src)[9] > $tpdf) {
                $why = 'source is newer';
            } else {
                for my $png (glob "$figdir/$name-*.png") {
                    if ((stat $png)[9] > $tpdf) { $why = 'image is newer'; last; }
                }
            }
        }
        next unless $why;

        unlink $pdf, "figures_pdf/$name.md5";
        print "latexmkrc: rebuild $name ($why)\n";
        $stale++;
    }

    # A \input-ed picture is externalised under an auto-generated
    # figures_pdf/main-figureNN name that cannot be mapped back to its source,
    # so a regenerated appendix figure would otherwise keep a stale cache. If
    # any such source is newer than the oldest auto-named cache, drop them all;
    # they are only a handful and cheap to rebuild.
    my @auto = glob('figures_pdf/main-figure*.pdf');
    if (@auto) {
        my ($oldest) = sort { $a <=> $b } map { (stat $_)[9] } @auto;
        my $newest = 0;
        for my $src (@plain) {
            next unless -e $src;
            my $t = (stat $src)[9];
            $newest = $t if $t > $newest;
        }
        if ($newest > $oldest) {
            unlink @auto, glob('figures_pdf/main-figure*.md5');
            print "latexmkrc: rebuild " . scalar(@auto) .
                  " auto-named figure(s) (\\input source is newer)\n";
            $stale++;
        }
    }

    # latexmk does not track the cached PDFs, so a missing one is not on its own
    # a reason to rerun. Drop the target to force the pass that rebuilds them.
    if ($stale) {
        unlink 'main.pdf';
        print "latexmkrc: $stale figure(s) to rebuild\n";
    }
}
